### PR TITLE
handled term resize adapatively

### PR DESCRIPTION
**Pull request by 20015jjw**
This pull request is focused on __dynamic ui__.

I added a script to fetch the size of the terminal, and modified how should curses respond to the change.  This is a rough solution for now, but it beats a totally static term I think. 

I'm not sure if this would work properly on a Mac OS X, as I only tested it with terminator on a 64bit trusty machine.

If you need pull request done in Chinese, I'll translate. 

out

### CODE REVIEW

**Comment by 20015jjw** [comment]
Umm it appears my change of README.md is also being merged, which is I don't intend. I'm fairly new to github, so bear with me if you can. How do I undo this? Thanks.

**Comment by chaserhkj** [comment]
to undo, just commit a new commit to branch 20015jjw:master with reverted changes

You also better write sth like `revert change to README.md` in your commit log

**Comment by 20015jjw** [comment]
@chaserhkj Thanks. It's done.

**Comment by chaserhkj** [comment]
Just to point out, you attached vim .swp files in the commit, I don't think these're wanted files in a source repository.

Also, while modifying the readme back to original, are you sure you still want that gif demo image which is not referenced at all in any files in your commit?

**Comment by 20015jjw** [comment]
@chaserhjk Let me clean it up. I can add these to gitignore, right? Thanks.

**Comment by 20015jjw** [comment]
I noticed there's an update during this pull request? Do I need to do something?

**Comment by chaserhkj** [comment]
@20015jjw Github reports that this pull request contains merge conflicts.

So you'd better merge the upstream updated codes and solve the conflicts, cleanup things yourself before we can merge this PR for you.

**Comment by 20015jjw** [comment]
@chaserhkj Okay. So I should pull the updates and merge them myself, right? Thanks.

**Comment by 20015jjw** [comment]
Okay now it can be merged. Here's what it looks like.
out

**Comment by darknessomi** [comment]
In Darwin , change the size of the program will Crash
image

**Comment by 20015jjw** [comment]
@darknessomi Forgot to push xD. Now it's fixed.

**Comment by darknessomi** [comment]
Please keep right a little
image

if change the size too small will Crash
image

Thanks!

**Comment by 20015jjw** [comment]
@darknessomi  which screen were you at before the crash? the song list seems fine.

**Comment by darknessomi** [comment]
image

**Comment by 20015jjw** [comment]
@darknessomi okay. Mine only crashes in the help menu. Yours crash whenever the screen is too small? or just with the menu?

**Comment by darknessomi** [comment]
@20015jjw whenever the screen is too small ,all the menu will crash

**Comment by 20015jjw** [comment]
Fixed. 
Personally, I prefer to have the start of the menu at 1/10 of the term width. Now it is set to 1/5 as you asked. We can probably let the user to pick where they want to align the header of the player?

**Comment by darknessomi** [comment]
Thank Fixed. I think most people like to show UI in the centered

**Comment by 20015jjw** [comment]
@darknessomi
If you think this works now, you can merge it. Having it always centered can be a bit tricky, so it may take some time.ok just open another PR when its dkne.

**Comment by darknessomi** [comment]
Anyway, dynamic ui is a big step,merged.
Thanks a lot ! 😃

**Comment by 20015jjw** [comment]
Oh you might want to update the screenshot in README.md.
Thanks you for merging! It's my first PR on github!

**Pull request merged**
